### ISSUE TITLE
Using probabilistic comparisons as training data

### ISSUE THREAD

**Issue by vmando** [lucasmaystre/choix#12]
Hi! Thanks for the great package. Is there a way to train the Bradley-Terry model starting from probabilistic data? E.g. one training sample might be" "item A is preferred to item B with probability 0.7."

**Comment by lucasmaystre** [comment]
Hi @vmando excellent question. This is not (yet?) possible with choix, but someone asked the exact same question on stack exchange a while ago, and I provided a code snippet that can be used to do this. See: https://datascience.stackexchange.com/a/19079/32417

Hope this helps.

**Comment by vmando** [comment]
Thank you! Will take a look into that.
