### ISSUE TITLE
Thank you for the excellent library!

### ISSUE THREAD

**Issue by Kobold** [lucasmaystre/choix#13]
No real issue and you can close this issue, but thank you so much for the library! I knew I needed a Bradley-Terry implementation in Python and went searching expecting to find just code snippets, not a whole nice library! The API and documentation are great.

**Comment by sethtroisi** [comment]
Mirroring this comment, I wanted something better than ELO and this library has been super useful with only minor gotchas.

**Comment by lucasmaystre** [comment]
Hi @Kobold and @sethtroisi thanks for the kind words!

Is there anything you'd find useful to have in the library / any ideas for improvements?

If you're using the library for player rating, you might potentially be interested in kickscore, another lib I'm working on that handles time-varying parameters:
https://github.com/lucasmaystre/kickscore

(Though it's a bit less stable and there's no documentation for now)

**Comment by sethtroisi** [comment]
@lucasmaystre 
One of the strong points of choix is the good documentation. I also appreciated your support In https://github.com/lucasmaystre/choix/issues/9

I'm using choix for AI ratings in Go, we break out each version as a seperate "player" so there should be no time varying component.

For useful features:
* I have lots of games ~300K if I don't pass good starting points it takes ~~2 minutes which could always be faster but certainly isn't a blocking anything right now
  * Most of my pairs have 20+ games played, maybe something could be improved here
* I've written a dynamic pairing program a couple of times and it always has issues. input is all games played (and potentially a estimate of rating for players without many games) and output is a set of matchups that will reduce uncertainty.

**Comment by lucasmaystre** [comment]
@sethtroisi thanks for the input. Point 1 (computational efficiency) is on my TODO list, I hope to be able to get to this soon. Will create an issue to track this.
