### ISSUE TITLE
Handling ties

### ISSUE THREAD

**Issue by AlessandroChecco** [lucasmaystre/choix#17]
In your paper you claim to extend the BTL for ties using P.V.Rao and L.L.Kupper paper. I was wondering if it's possible to implement it here.

Thanks!

**Comment by lucasmaystre** [comment]
Hi @AlessandroChecco sorry for the delay.

Yes it'd be possible to implement it. I don't have the cycles right now, but I'll keep the issue open as a reminder to implement it at some point.

In the meantime, here are two suggestions if you need to fit a Rao-Kupper model right away.

## Using choix

You can preprocess the data by transforming every tie (say `a = b`) into two outcomes (`a > b` and `b > a`) and then simply fit a Bradley-Terry model using `choix`. This is exactly equivalent to a Rao-Kupper model in the limit of theta -> 0 (where theta is the "draw margin") and in practice it works quite well.

## Using kickscore

I am also maintaining another library, [kickscore](https://github.com/lucasmaystre/kickscore), that lets you fit a Rao-Kupper with an arbitrary draw margin.

Here's a short snippet:

    import kickscore as ks
    model = ks.TernaryModel(margin=0.1, obs_type="logit")
    k = ks.kernel.Constant(var=1.0)

    model.add_item("a", kernel=k)
    model.add_item("b", kernel=k)
    model.add_item("c", kernel=k)

    model.observe(winners=["a"], losers=["b"], t=0.0)
    model.observe(winners=["b"], losers=["c"], t=0.0, tie=True)

    model.fit(verbose=True)

    ms, vs = model.item["a"].predict([0.0])
    score = ms[0]

There are two hyperparameters to tune, `margin` (the draw margin) and `var` (the prior variance). A good way to select these hyperparameters is to try to maximize the marginal log-likelihood, which you can get using

    model.log_likelihood
