### ISSUE TITLE
Missing link to Bayesian example network

### ISSUE THREAD

**Issue by roy7** [lucasmaystre/choix#19]
The link to the example (https://pypi.org/project/choix/notebooks/ep-example.ipynb) doesn't exist.

**Comment by roy7** [comment]
Ah, I'm referring to the page https://pypi.org/project/choix/. It works within the github itself.

The correct link is https://github.com/lucasmaystre/choix/blob/master/notebooks/ep-example.ipynb.

**Comment by lucasmaystre** [comment]
@roy7 thanks for reporting!
