### ISSUE TITLE
Ties in rankings

### ISSUE THREAD

**Issue by rkmaddox** [lucasmaystre/choix#23]
I see in #17 some suggestions for handling ties in pairwise comparisons. Is there a way to do that in rankings? Specifically, I have a case where several competitors in a race may not finish, and all of the should be ranked as number of finishers + 1. Is there a way to handle such a condition?

**Comment by lucasmaystre** [comment]
Apologies for the (very!) delayed reply. The situation you describe can be handled with [top-1 lists](https://choix.lum.li/en/latest/data.html#top-1-lists).

For example, if you have the situation where 0, 1, 2 finish the race (in this order), and 3, 4, 5 did not finish (let's write this as: `item0 > item1 > item2 > {item3, item4, item5}`), you could do something like

```
import choix
data = [
    [0, {1, 2, 3, 4, 5}],
    [1, {2, 3, 4, 5}],
    [2, {3, 4, 5}],
]

params = choix.opt_top1(n_items=6, data)
```
