### ISSUE TITLE
Understanding the islr_pairwise behaviour

### ISSUE THREAD

**Issue by gazzza** [lucasmaystre/choix#3]
I followed the code in your intro notebook

# Infer Bradley-Terry model parameters.
est = choix.ilsr_pairwise(n_items, data, alpha=1e-3)

# Ranking of the items (from worst to best)
ranking = np.argsort(est)

using the following data:

data = [(0, 1),
(0, 2),
(0, 3),
(1, 2),
(1, 3),
(2, 3)]

which produced the following output:

[ 0.02440682  0.00827314 -0.00812072 -0.02478326  0.00011201  0.00011201]
('ranking (worst to best):', array([3, 2, 4, 5, 1, 0]))

I am mainly wondering how the ranking part of the algorithm works:

My understanding was that this algorithm should produce a rank of [0, 1, 2], since 0 is the best player in this case. Clearly this is not what is happening, so what are the params actually calculating, and how would I get the ranking as I want above?

**Comment by lucasmaystre** [comment]
Hi @gazzza , sorry for not getting back to you earlier. Actually, the ranking *does* say that zero is the best item: the ranking is **worst** to **best**.

If you want it in the order *best to worst*, you could just use

    np.argsort(params)[::-1]
