### ISSUE TITLE
Unexpected argument 'alpha' for opt_pairwise

### ISSUE THREAD

**Issue by victorkristof** [lucasmaystre/choix#5]
Hi @lucasmaystre,

When using `choix.opt_pairwise`, setting `alpha` raises an error:

```
TypeError: opt_pairwise() got an unexpected keyword argument 'alpha'
```

But the [doc](http://choix.lum.li/en/latest/api.html#choix.opt_pairwise) suggests it should be possible to set it :)

Example code:

```
import choix

n_items = 5
data = [
    (1, 0), (0, 4), (3, 1),
    (0, 2), (2, 4), (4, 3),
]

choix.opt_pairwise(n_items, data, alpha=0.1)
```

**Comment by lucasmaystre** [comment]
Hi @victorkristof ,
you might be using an old version of the library. The change that introduces that parameter is "only" 7 months old:
https://github.com/lucasmaystre/choix/commit/4ae8793888b563d26ceec4b70dfb590ed9332be1

**Comment by victorkristof** [comment]
Makes perfectly sense - updating the library solved it, thanks!
