### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by tamos** [lucasmaystre/choix#8]
Do you have a paper I can cite if I use choix in my work?

**Comment by lucasmaystre** [comment]
Hi @tamos , thanks for the question! You can cite my [thesis](https://infoscience.epfl.ch/record/255399), which describes the library at a high level.

> Lucas Maystre. *Efficient Learning from Comparisons*. PhD thesis, École Polytechnique Fédérale de Lausanne, 2018.

    @phdthesis{maystre2018efficient,
      author = "Maystre, Lucas",
      title = "Efficient Learning from Comparisons",
      school = "École Polytechnique Fédérale de Lausanne",
      year = 2018,
    }
